// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaInspecciones.Infrastructure.Data;

#nullable disable

namespace SistemaInspecciones.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260807223750_InicialCreate")]
    partial class InicialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SistemaInspecciones.Domain.Entities.Audio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DuracionSegundos")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("InspeccionId")
                        .HasColumnType("int");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoContenido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("InspeccionId");

                    b.ToTable("Audios", (string)null);
                });

            modelBuilder.Entity("SistemaInspecciones.Domain.Entities.Fotografia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("InspeccionId")
                        .HasColumnType("int");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoContenido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("InspeccionId");

                    b.ToTable("Fotografias", (string)null);
                });

            modelBuilder.Entity("SistemaInspecciones.Domain.Entities.HistorialInspeccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Detalle")
                        .HasColumnType("text");

                    b.Property<string>("EstadoAnterior")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("EstadoNuevo")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("InspeccionId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InspeccionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("HistorialInspecciones", (string)null);
                });

            modelBuilder.Entity("SistemaInspecciones.Domain.Entities.Inspeccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DireccionReferencia")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaInspeccion")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("Latitud")
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal?>("Longitud")
                        .HasColumnType("decimal(11,8)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Inspecciones", (string)null);
                });

            modelBuilder.Entity("SistemaInspecciones.Domain.Entities.Observacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("InspeccionId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InspeccionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Observaciones", (string)null);
                });

            modelBuilder.Entity("SistemaInspecciones.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("SistemaInspecciones.Domain.Entities.Audio", b =>
                {
                    b.HasOne("SistemaInspecciones.Domain.Entities.Inspeccion", "Inspeccion")
                        .WithMany("Audios")
                        .HasForeignKey("InspeccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inspeccion");
                });

            modelBuilder.Entity("SistemaInspecciones.Domain.Entities.Fotografia", b =>
                {
                    b.HasOne("SistemaInspecciones.Domain.Entities.Inspeccion", "Inspeccion")
                        .WithMany("Fotografias")
                        .HasForeignKey("InspeccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inspeccion");
                });

            modelBuilder.Entity("SistemaInspecciones.Domain.Entities.HistorialInspeccion", b =>
                {
                    b.HasOne("SistemaInspecciones.Domain.Entities.Inspeccion", "Inspeccion")
                        .WithMany("HistorialInspecciones")
                        .HasForeignKey("InspeccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaInspecciones.Domain.Entities.Usuario", "Usuario")
                        .WithMany("HistorialInspecciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Inspeccion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaInspecciones.Domain.Entities.Inspeccion", b =>
                {
                    b.HasOne("SistemaInspecciones.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Inspecciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaInspecciones.Domain.Entities.Observacion", b =>
                {
                    b.HasOne("SistemaInspecciones.Domain.Entities.Inspeccion", "Inspeccion")
                        .WithMany("Observaciones")
                        .HasForeignKey("InspeccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaInspecciones.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Observaciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Inspeccion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaInspecciones.Domain.Entities.Inspeccion", b =>
                {
                    b.Navigation("Audios");

                    b.Navigation("Fotografias");

                    b.Navigation("HistorialInspecciones");

                    b.Navigation("Observaciones");
                });

            modelBuilder.Entity("SistemaInspecciones.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("HistorialInspecciones");

                    b.Navigation("Inspecciones");

                    b.Navigation("Observaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
